### ISSUE TITLE
Make URL of rest-endpoint fully configurable

### ISSUE THREAD

**Issue by sebastiansirch** [livetocode/camunda-prometheus-exporter#2]
Hi,

currently the "-server" parameter assumes that the rest endpoint is running on "/engine-rest" which might not be the case. For example, when you use camunda with spring boot, the default is "/rest". So I would suggest to move the root-path of the rest endpoint from the sources to the server parameter such that "-server=http://my.camunda.server/rest" would be a typical value.

Best,
Sebastian

**Comment by livetocode** [comment]
I've added a -restPrefix param which defaults to "rest".

**Comment by AndreaGiardini** [comment]
Can we consider this issue closed by https://github.com/livetocode/camunda-prometheus-exporter/commit/ae2055a07bddc8436cc2680d470400e1c9245600 ? @sebastiansirch

**Comment by sebastiansirch** [comment]
yep, thanks!
